package main

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/Arman2122/p-ui/internal/core"
)

// emitCapabilities writes the capability rule table as TypeScript data. The
// rules are evaluated by both languages, so generating them here is what keeps
// "may this inbound do X" from acquiring a fourth hand-written implementation.
func emitCapabilities(w io.Writer) error {
	encoded, err := json.MarshalIndent(core.CapabilityRules(), "", "  ")
	if err != nil {
		return err
	}
	names, err := json.Marshal(core.CapabilityNames())
	if err != nil {
		return err
	}

	if _, err := fmt.Fprint(w, "// Code generated by tools/openapigen. DO NOT EDIT.\n"); err != nil {
		return err
	}
	if _, err := fmt.Fprint(w, "// Source of truth: internal/core/capability.go. Evaluate with src/lib/cores/capabilities.ts.\n\n"); err != nil {
		return err
	}
	if _, err := fmt.Fprint(w, "export type CapabilityOp = 'in' | 'set' | 'prefix';\n\n"); err != nil {
		return err
	}
	if _, err := fmt.Fprint(w, "export interface CapabilityClause {\n  field: string;\n  op: CapabilityOp;\n  values?: string[];\n  not?: boolean;\n}\n\n"); err != nil {
		return err
	}
	if _, err := fmt.Fprint(w, "export interface CapabilityTerm {\n  all: CapabilityClause[];\n}\n\n"); err != nil {
		return err
	}
	if _, err := fmt.Fprint(w, "export interface CapabilityRule {\n  any: CapabilityTerm[];\n}\n\n"); err != nil {
		return err
	}
	if _, err := fmt.Fprintf(w, "export const CAPABILITY_NAMES = %s as const;\n\n", names); err != nil {
		return err
	}
	credentials, err := json.Marshal(core.ClientCredentialNames())
	if err != nil {
		return err
	}
	if _, err := fmt.Fprint(w, "// Source of truth: internal/core/credentials.go. A core declares a subset per kind.\n"); err != nil {
		return err
	}
	if _, err := fmt.Fprintf(w, "export const CLIENT_CREDENTIAL_NAMES = %s as const;\n\n", credentials); err != nil {
		return err
	}
	if _, err := fmt.Fprint(w, "export type ClientCredentialName = (typeof CLIENT_CREDENTIAL_NAMES)[number];\n\n"); err != nil {
		return err
	}
	if _, err := fmt.Fprintf(w, "export const CAPABILITY_RULES: Record<string, CapabilityRule> = %s;\n", encoded); err != nil {
		return err
	}
	return nil
}
